package de.enflexit.ea.electricity.transformer;

public enum ActuatorGoal {
	REDUCE_LOAD,
	REDUCE_FEED_IN,
	INCREASE_LOAD,
	INCREASE_FEED_IN,
	LOWER_VOLTAGE_VIOLATION, 
	INCREASE_VOLTAGE, 
	UNFREEZE_PROPOSAL, 
	IRRELEVANT,
	CABLE_OVERLOAD,
	UPPER_VOLTAGE_VIOLATION,
	LOWER_VOLTAGEVIOLATION,
	VOLTAGE_ADJUSTMENT;
}
